### ISSUE TITLE
In response to OpenStreetMap redaction in Peru / En respuesta a la redacción de OpenStreetMap en Perú

### ISSUE THREAD

**Issue by piligab** [osm-pe/osm-peru-redaction#1]
## ENGLISH VERSION 
The [DWG](https://wiki.openstreetmap.org/wiki/Data_working_group) has received a notification of [copyright infringement](http://dmca.openstreetmap.org/), alleging that some data has been copied to OpenStreetMap, affecting Peru.

6 or 7 years ago, the user [TELECOM IP](https://www.openstreetmap.org/user/TELCOM%20IP) made an import of private data, those imports was made in around 28 cities of Peru. [TELECOM IP](https://www.openstreetmap.org/user/TELCOM%20IP) could not verify the [origin and the license of the data](https://www.openstreetmap.org/changeset/7218867), so the company Guiacalles that registered the claim, showed that the data came from them (using, among other methods, some streets of the trap https://es.wikipedia.org/wiki/Calle_trampa).

The imported OSM data were analyzed and verified by DWG and they decided to do the redaction - https://www.openstreetmap.org/redactions/101, which should finish in 2 weeks. So far  there are [many places affected.](https://osmcha.mapbox.com/changesets/55895426?filters=%7B%22in_bbox%22%3A%5B%7B%22label%22%3A%22-87.5804%2C-18.5259%2C-68.5073%2C0.2157%22%2C%22value%22%3A%22-87.5804%2C-18.5259%2C-68.5073%2C0.2157%22%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22Redact%22%2C%22value%22%3A%22Redact%22%7D%5D%7D)

<img width="1186" alt="screen shot 2018-01-30 at 6 07 41 pm" src="https://user-images.githubusercontent.com/1152236/35596609-93a4eb36-05e8-11e8-8822-ff1c82ee0a5a.png">

- https://www.openstreetmap.org/edit#map=17/-12.05974/-75.22721 
- https://www.openstreetmap.org/edit#map=17/-16.39974/-71.54168

**The OSM Peru community is waiting until the redaction finished to start repairing all the affected places.So far there are starting some actions.**

- [ ] Creations of  task with the areas affected (according to [naoliv](https://www.openstreetmap.org/user/naoliv)).

We are going to report on this ticket every next actions to start the fix affected places, join us to [Telegram](https://web.telegram.org/#/im?p=@osmPe) to make the coordination of the efforts. :muscle: 

*If you have any comment or suggestion please post on this ticket!* :rocket: 

## SPANISH VERSION 
La [DWG](https://wiki.openstreetmap.org/wiki/Data_working_group) ha recibido una notificación de infracción de derechos de autor (a través de http://dmca.openstreetmap.org/), alegando que algunos datos se han copiado a OpenStreetMap, afectando al Perú.

Hace 6 o 7 años, el usuario [TELECOM IP](https://www.openstreetmap.org/user/TELCOM%20IP) realizó una importación de datos privados, esas importaciones se realizaron en alrededor de 28 ciudades del Perú. [TELECOM IP](https://www.openstreetmap.org/user/TELCOM%20IP) no pudo verificar el [origen y la licencia de los datos] (https://www.openstreetmap.org/changeset/7218867), es así que la empresa Guiacalles, quien registró el reclamo, mostró que los datos provenían de ellos (utilizando, entre otros métodos, algunas calles de la trampa https://es.wikipedia.org/wiki/Calle_trampa).

Los datos importados de OSM fueron analizados y verificados por DWG y decidieron hacer la redacción - https://www.openstreetmap.org/redactions/101, que debería finalizar en 2 semanas. Hasta ahora hay [muchos lugares afectados.](https://osmcha.mapbox.com/changesets/55895426?filters=%7B%22in_bbox%22%3A%5B%7B%22label%22%3A%22-87.5804%2C-18.5259%2C-68.5073%2C0.2157%22%2C%22value%22%3A%22-87.5804%2C-18.5259%2C-68.5073%2C0.2157%22%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22Redact%22%2C%22value%22%3A%22Redact%22%7D%5D%7D)

<img width="1186" alt="screen shot 2018-01-30 at 6 07 41 pm" src="https://user-images.githubusercontent.com/1152236/35596609-93a4eb36-05e8-11e8-8822-ff1c82ee0a5a.png">

- https://www.openstreetmap.org/edit#map=17/-12.05974/-75.22721 
- https://www.openstreetmap.org/edit#map=17/-16.39974/-71.54168

**La comunidad de OSM Perú está esperando hasta que la redacción finalice para comenzar a reparar todos los lugares afectados. Hasta ahora están comenzando algunas acciones.**

- [ ] Crear una tarea con las áreas afectadas (de acuerdo a [naoliv](https://www.openstreetmap.org/user/naoliv)) 

Vamos a informar en este ticket sobre las siguientes acciones para iniciar la reparación de los lugares afectados, únete a [Telegram](https://web.telegram.org//im?p=@osmPe) para hacer la coordinación de los esfuerzos. :muscle: 

*Si tiene algún comentario o sugerencia, por favor publique un comentario en este ticket!.* :rocket: 

cc. @olafveerman @Rub21 @naoliv @johnarupire @ovruni @yachaqruna @ediyes @dannykath @ridixcr @calfarome @RichRico @karitotp

**Comment by naoliv** [comment]
As soon as the redaction ends I will provide the task link (it's already done, I just need to publish it), affected places/cities names, changesets and a GeoJSON with the areas (I can also provide a shapefile, if needed, or any other format as you wish).

If there is anything else that you would like to have, and that I can prepare in advance, just tell me, please.

**Comment by naoliv** [comment]
The task with the affected areas for mapping is now available at https://tareas.openstreetmap.co/project/96
I owe Kleper, from OpenStreetMap Colombia, a big thanks for kindly providing the service.

The list of affected cities that will need to be reviewed is already known, at https://github.com/osm-pe/osm-peru-redaction/issues/3

I have marked the cities with a higher priority (which should be mapped first) in tha task manager.
Some areas are big and most probably you will need to split them into smaller parts using the task manager.

One important thing to warn is that we **must not** retrace any object using the old data (even if it's still visible in an outdated layer), with the risk of having to remove the objects again.

Ways without a `highway` or other tag can be reused, instead deleting them to retrace again.
It's also possible to reuse unconnected nodes, if present.

A GeoJSON with the affected areas is also avaliable at https://gist.github.com/naoliv/86555af0f9b6bcc86e69b4421e216fbb

A more detailed view of the changesets that had to be redacted, if needed for some reason:

|Changeset|Affected area/city|
|---|---|
|6911399|Trujillo|
|6940947|Trujillo|
|6942459|Trujillo|
|6947530|Chimbote|
|6948870|Chimbote|
|6950478|Chimbote|
|6951354|Tumbes|
|6952064|Bagua Grande|
|6952116|Arequipa|
|6978048|Cajamarca|
|6978981|Chachapoyas|
|7218867|Jaen|
|7377129|Yungay|
|7377212|Juanjuí|
|7377327|Moyobamba|
|7377468|Tarma|
|7378822|Talara|
|7424220|Huaral|
|7468887|Tarapoto|
|7468963|Huaraz/Carhuaz|
|7484868|Paita|
|7561364|Huacho|
|7561648|Sullana|
|7566847|Pueblo Nuevo/Chincha Alta|
|7591242|Ica|
|7591310|Piura|
|7607654|Huancayo|
|7627808|Tacna|
|7701159|Huancayo|
|7707346|Arequipa|
|7767564|Chiclayo|
|7808146|Arequipa|
|7917481|Chiclayo|
|7919406|Arequipa|
|7921214|Lima|
|7921431|Lima|
|7921581|Lima|
|7921728|Lima|
|7921891|Lima|
|7922147|Lima|
|7955868|Lima|
|7999118|Arequipa|
|7999341|Arequipa|
|7999736|Arequipa|
|8003731|Yungay|
|8003787|Moyobamba|
|8003855|Tarma|
|8003976|Talara|
|8004108|Paita|
|8004392|Tacna|
|8004672|Some highways spread in Peru|
|8060354|Lima|
|8061144|Lima|
|8061633|Lima|
|8061899|Lima|
|8062075|Lima|
|8062186|Lima|
|8062310|Lima|
|8062754|Lima|

**Comment by Rub21** [comment]
I think there were 145 redaction changesets: https://osmcha.mapbox.com/changesets/55991053?filters=%7B%22in_bbox%22%3A%5B%7B%22label%22%3A%22-87.5804%2C-18.5259%2C-68.5073%2C0.2157%22%2C%22value%22%3A%22-87.5804%2C-18.5259%2C-68.5073%2C0.2157%22%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22Redact%22%2C%22value%22%3A%22Redact%22%7D%5D%7D

**Comment by naoliv** [comment]
That number (and the changesets where the data was reverted/deleted) won't really matter, I think.
The redaction works in 2 steps: first the objects need to be reverted to their previous state (or deleted; that is why you see these changesets with up to 1000 objects each).
Then the redaction itself, where the objects are are actually removed from the database (this doesn't generate any kind of changeset).

**Comment by piligab** [comment]
We already have the task prepared based on the affected areas, [here the workflow](https://github.com/osm-pe/osm-peru-redaction/issues/4). We can start mapping  :rocket:

**Comment by piligab** [comment]
We finished to [map](https://github.com/osm-pe/osm-peru-redaction/issues/4#issuecomment-375848860) and [valid](https://github.com/osm-pe/osm-peru-redaction/issues/4#issuecomment-382185291) the task. :rocket: 

No more actions here!
