### ISSUE TITLE
Ciudades afectadas por la reversión 

### ISSUE THREAD

**Issue by Rub21** [osm-pe/osm-peru-redaction#3]
Aqui dejo la lista de ciudades que estan siendo afectadas por a reversion.

- [Arequipa](https://www.openstreetmap.org/search?query=Arequipa)
- [Bagua Grande](https://www.openstreetmap.org/search?query=Bagua%20Grande)
- [Cajamarca](https://www.openstreetmap.org/search?query=Cajamarca)
- [Chachapoyas](https://www.openstreetmap.org/search?query=Chachapoyas)
- [Chiclayo](https://www.openstreetmap.org/search?query=Chiclayo)
- [Chimbote](https://www.openstreetmap.org/search?query=Chimbote)
- [Huacho](https://www.openstreetmap.org/search?query=Huacho)
- [Huancayo](https://www.openstreetmap.org/search?query=Huancayo)
- [Huaral](https://www.openstreetmap.org/search?query=Huaral)
- [Huaraz/Carhuaz](https://www.openstreetmap.org/search?query=Huaraz/Carhuaz)
- [Ica](https://www.openstreetmap.org/search?query=Ica)
- [Jaen](https://www.openstreetmap.org/search?query=Jaen)
- [Juanjuí](https://www.openstreetmap.org/search?query=Juanjuí)
- [Lima](https://www.openstreetmap.org/search?query=Lima)
- [Moyobamba](https://www.openstreetmap.org/search?query=Moyobamba)
- [Paita](https://www.openstreetmap.org/search?query=Paita)
- [Piura](https://www.openstreetmap.org/search?query=Piura)
- [Pueblo Nuevo/Chincha Alta](https://www.openstreetmap.org/search?query=Pueblo%20Nuevo/Chincha%20Alta)
- [Sullana](https://www.openstreetmap.org/search?query=Sullana)
- [Tacna](https://www.openstreetmap.org/search?query=Tacna)
- [Talara](https://www.openstreetmap.org/search?query=Talara)
- [Tarapoto](https://www.openstreetmap.org/search?query=Tarapoto)
- [Tarma](https://www.openstreetmap.org/search?query=Tarma)
- [Trujillo](https://www.openstreetmap.org/search?query=Trujillo)
- [Tumbes](https://www.openstreetmap.org/search?query=Tumbes)
- [Yungay](https://www.openstreetmap.org/search?query=Yungay)

cc. @ovruni @rdacardenas @sguinetti @piligab

**Comment by sguinetti** [comment]
Estoy al tanto en Arequipa. Aun dudo si revertirán las ediciones

**Comment by ovruni** [comment]
Ya he agregado las calles de Tacna (aun faltan algunas al sur de la ciudad) y de Tumbes, ahora me pongo a agregar las de Chiclayo

**Comment by piligab** [comment]
We finished to [map](https://github.com/osm-pe/osm-peru-redaction/issues/4#issuecomment-375848860) and [valid](https://github.com/osm-pe/osm-peru-redaction/issues/4#issuecomment-382185291) all the areas. :rocket: 

No more actions here!
