### ISSUE TITLE
Flujo de trabajo para mapear los lugares afectados de la reversion /Workflow for mapping the affected places of the reaction

### ISSUE THREAD

**Issue by piligab** [osm-pe/osm-peru-redaction#4]
From: https://github.com/osm-pe/osm-peru-redaction/issues/1

:wave: Hola con todos, ya tenemos la [tarea](https://tareas.openstreetmap.co/project/96) preparada con base en las zonas afectadas, aquí el flujo de trabajo. Ya podemos empezar a mapear :rocket: 

:wave: Hi everyone, we already have the [task](https://tareas.openstreetmap.co/project/96) prepared based on the affected areas, here the workflow. We can start mapping :rocket: 

### 1. FLUJO DE TRABAJO

- Ingresar a la tarea https://tareas.openstreetmap.co/project/96

- Seleccionar un cuadro para iniciar a trabajar (para evitar conflictos, cada uno de nosotros debería trabajar en diferentes ciudades)

- Agregar el TMS `https://api.mapbox.com/styles/v1/ridixcr/cjdablkb0524w2rqhpms0ht1w/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoicmlkaXhjciIsImEiOiJ1cDdkcU5BIn0.V-0Q657lFqPBZ3IaHGsDng`, capa para identificar las áreas afectadas. 

![addtmslayer](https://user-images.githubusercontent.com/19536044/35815081-b5123eb4-0a65-11e8-864f-031b548bfae7.gif)

- Agregar WMS `http://sige.inei.gob.pe/cgi-bin/mapserv?map=/var/www/html/test/atlas/map/mapa_negocios_cp.map`, capa para agregar nombres de calles, más detalles de como agregar la capa aquí https://github.com/osm-pe/mapping/issues/1.

- Mapear todas las calles que fueron afectadas. El TMS anterior ayuda a identificar las áreas afectadas en las que debemos enfocarnos, como se muestra en la siguiente imagen:

![selection_068](https://user-images.githubusercontent.com/19536044/35814320-c4312808-0a63-11e8-8829-6d193770f8e6.png)

**CASOS COMUNES:**
- Si encuentra calles desconectadas, debemos conectarlas (según sea el caso)
- Si encuentra calles sin la etiqueta "highway", agregar la etiqueta según corresponda.
- En caso de nodos sueltos sobre calles, pueden conectarse entre ellos o eliminarlos y volver a trazar la calle.
- Si encuentra calles desalineadas en la zona afectada debemos alinearlos.

### - FUENTE

- Bing, http://sige.inei.gob.pe/test/atlas/

### - COMENTARIO DE LOS CAMBIOS

- Agregado calles que fueron eliminadas por la reversión, #missinghighways #Peru

### 1. WORKFLOW

- Go to task: https://tareas.openstreetmap.co/project/96

- Select a box to start working (to avoid conflicts, each of us should work in different cities).

- Add the TMS `https://api.mapbox.com/styles/v1/ridixcr/cjdablkb0524w2rqhpms0ht1w/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoicmlkaXhjciIsImEiOiJ1cDdkcU5BIn0.V-0Q657lFqPBZ3IaHGsDng`, layer to identify the affected areas.

![addtmslayer](https://user-images.githubusercontent.com/19536044/35815081-b5123eb4-0a65-11e8-864f-031b548bfae7.gif)

- Add the WMS `http://sige.inei.gob.pe/cgi-bin/mapserv?map=/var/www/html/test/atlas/map/mapa_negocios_cp.map`, layer to add highway names, more details to add this layer here https://github.com/osm-pe/mapping/issues/1.

- Map all the highways that were affected. The previous TMS helps identify the affected areas on which we should focus, as shown in the below image:

![selection_068](https://user-images.githubusercontent.com/19536044/35814320-c4312808-0a63-11e8-8829-6d193770f8e6.png)

**COMMON CASES:**
- If you find highways disconnected, we must connect them (as the case may be).
- If you find a highway without "highway" tag, add the tag as appropriate.
- In case of loose nodes on highway, you can connect to each other or delete them and map again the highway.
- If you find misaligned highway in the affected area, we must align them.

### - SOURCE

- Bing, http://sige.inei.gob.pe/test/atlas/

### - CHANGESET COMMENT 

- Agregado calles que fueron eliminadas por la reversión, #missinghighways #Peru

cc. @Rub21 @johnarupire @ovruni @yachaqruna @ediyes @dannykath @ridixcr @calfarome @RichRico @karitotp @sguinetti @rdacardenas

**Comment by ridixcr** [comment]
Debido a que la anterior capa TMS ya no funciona :point_down: 
> `https://api.mapbox.com/styles/v1/ridixcr/cjdablkb0524w2rqhpms0ht1w/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoicmlkaXhjciIsImEiOiJ1cDdkcU5BIn0.V-0Q657lFqPBZ3IaHGsDng`

Se creo esta otra capa TMS :heavy_check_mark: 

`https://api.mapbox.com/styles/v1/devseed/cjeyarec118e02rt6d8f10p6p/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZGV2c2VlZCIsImEiOiJnUi1mbkVvIn0.018aLhX0Mb0tdtaT2QNe2Q`

![](https://user-images.githubusercontent.com/1646072/37615686-e42f2f54-2b7b-11e8-9c5f-14b07c4b39b4.gif)

**Comment by karitotp** [comment]
The task was finished :tada:, thanks to everybody who worked to repair the map of Perú! :clap: 
![screenshot from 2018-03-24 00-23-25](https://user-images.githubusercontent.com/11504548/37860738-f9193118-2ef9-11e8-915b-f1b914992774.png)

Now the validations is in 11% and we will validate the 100% of tasks to make sure that all the affected highways were fixed :rocket:

**Comment by dannykath** [comment]
About the validation now we are on 22%, we added and modified *2,661*   highways. Thank you everybody who worked on validate the map of Peru!

**Comment by karitotp** [comment]
Finally all the task was validated! :tada: 

![screenshot from 2018-04-17 17-33-09](https://user-images.githubusercontent.com/11504548/38902712-4f3efb60-4267-11e8-8035-8f78df67f11a.png)

Since this task was published and shared with the community, more than 95 000 highways were modified and added in all Peru.

Special thanks to everyone who contributed to this task. Great work! :clap:

**Comment by piligab** [comment]
Finally, @karitotp wrote a [OSM diary](https://www.openstreetmap.org/user/karitotp/diary/43824) :rocket: 

No more actions here!!
